name: kibisis
description: "Kibisis Mobile App"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^13.2.2
  shared_preferences: ^2.2.3
  loading_overlay: ^0.3.0
  flutter_svg: ^2.0.10+1
  ellipsized_text: ^1.2.0
  pin_input_text_field: ^4.5.1
  cupertino_icons: ^1.0.6
  algorand_dart: ^1.0.3
  gradient_borders: ^1.0.0
  flutter_secure_storage: ^9.0.0
  convert: ^3.1.1
  crypto: ^3.0.1
  flutter_native_splash: ^2.4.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Anonymous Pro
      fonts:
        - asset: assets/fonts/AnonymousPro-Regular.ttf
        - asset: assets/fonts/AnonymousPro-Bold.ttf
          weight: 700
