name: kibisis
description: "Kibisis Mobile App"
publish_to: 'none'
version: 0.3.0+4
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^13.2.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  ellipsized_text: ^1.2.0
  cupertino_icons: ^1.0.6
  algorand_dart: ^1.0.3
  gradient_borders: ^1.0.0
  flutter_secure_storage: ^9.0.0
  convert: ^3.1.1
  crypto: ^3.0.1
  flutter_native_splash: ^2.4.0
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.1.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  infinite_carousel: ^1.1.1
  vibration: ^1.8.4
  percent_indicator: ^4.2.3
  http: ^1.2.2
  card_swiper: ^3.0.1
  base32: ^2.1.3
  connectivity_plus: ^6.0.5
  flutter_expandable_fab: ^2.2.0
  mobile_scanner: ^5.1.1
  walletconnect_flutter_v2: ^2.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#1A202C"
  image: "assets/images/splash-logo.png"
  android_12:
    image: "assets/images/splash-logo.png"
    color: "#1A202C"
  android: true
  ios: true
  web: true
  fullscreen: true 


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FF8D029B"
    theme_color: "#FFFFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  # fonts:
  #   - family: Anonymous Pro
  #     fonts:
  #       - asset: assets/fonts/AnonymousPro-Regular.ttf
  #       - asset: assets/fonts/AnonymousPro-Bold.ttf
  #         weight: 700

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700