name: "Use Flutter Dependencies"
description: "Installs the Flutter SDK and project dependencies with caching."

runs:
  using: "composite"
  steps:
    - name: "☕ Set up Java"
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "zulu"
    - name: "🔧 Setup Flutter"
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.22.3
        channel: stable
    - name: "📦 Cache Pub Dependencies"
      id: pub-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ${{ runner.workspace }}/.packages
        key: flutter-pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          flutter-pub-${{ runner.os }}-
    - name: "📦 Install Dependencies"
      if: steps.pub-cache.outputs.cache-hit != 'true'  # only run if the dependencies cache is not found
      run: flutter pub get
      shell: bash
