name: "Deploy - Production"

on:
  release:
    types: [released] # triggered on main branch releases

jobs:
  deploy:
    name: "🚀 Deploy"
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
    secrets:
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
