name: "Deploy - Beta"

on:
  release:
    types: [prereleased] # triggered on beta branch releases

jobs:
  deploy:
    name: "🚀 Deploy"
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "beta"
    secrets:
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

