name: "Publish - Production"

on:
  release:
    types: [released] # triggered on main branch releases

jobs:
  deploy:
    name: "🚀 Publish"
    uses: ./.github/workflows/publish.yml
    with:
      environment: "production"
    secrets:
      PLAY_STORE_UPLOAD_KEY_ALIAS: ${{ secrets.PLAY_STORE_UPLOAD_KEY_ALIAS }}
      PLAY_STORE_UPLOAD_KEY_PASSWORD: ${{ secrets.PLAY_STORE_UPLOAD_KEY_PASSWORD }}
      PLAY_STORE_UPLOAD_KEYSTORE: ${{ secrets.PLAY_STORE_UPLOAD_KEYSTORE }}
      PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD: ${{ secrets.PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD }}
      GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
