name: "Publish"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      PLAY_STORE_UPLOAD_KEY_ALIAS:
        required: true
      PLAY_STORE_UPLOAD_KEY_PASSWORD:
        required: true
      PLAY_STORE_UPLOAD_KEYSTORE:
        required: true
      PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD:
        required: true
      GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY:
        required: true

jobs:
  publish_to_play_store:
    name: "Publish To The Play Store"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📱 Setup Flutter"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "💎 Setup Ruby"
        uses: ./.github/actions/use-ruby-dependencies
      - name: "🔑 Create Android Signing Keys"
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.PLAY_STORE_UPLOAD_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.PLAY_STORE_UPLOAD_KEY_PASSWORD }}
          ANDROID_KEYSTORE: ${{ secrets.PLAY_STORE_UPLOAD_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD }}
        run: ./scripts/create_android_signing_keys.sh
      - name: "🔑 Create Play Store Credentials"
        env:
          GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
        run: ./scripts/create_play_store_credentials.sh
      - name: "🏗️ Build AppBundle"
        run: flutter build aab --release
      - name: "🚀 Publish Via Fastlane"
        run: |
          cd ./android
          bundle exec fastlane ${{ inputs.environment }}
