name: "Deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_KEYSTORE:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true

jobs:
  deploy_to_play_store:
    name: "Deploy To The Play Store"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup Flutter"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🔑 Create Android signing keys"
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: ./scripts/create_android_signing_keys.sh
      - name: "🏗️ Build AppBundle"
        run: flutter build appbundle --release
      - name: " Deploy To Play Store"
        uses: r0adkll/upload-google-play@v1.0.18
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.example.app
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          track: internal
