name: "Pull Request Checks"

on:
  pull_request:

jobs:
  ##
  # install
  ##

  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies

  ##
  # validation
  ##

  validate_pr_title:
    name: "Validate PR Title"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "✅ Validate"
        run: echo ${{ github.event.pull_request.title }} | dart run commitlint_cli

  ##
  # build
  ##

  build_android:
    name: "Build Android"
    needs: [validate_pr_title]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🏗️ Build APK"
        run: flutter build apk --debug
      - name: "🏗️ Build AppBundle"
        run: flutter build aab --debug

#  build_ios:
#    name: "Build iOS"
#    needs: [validate_pr_title]
#    runs-on: macos-latest
#    environment: development
#    steps:
#      - name: "🛎 Checkout"
#        uses: actions/checkout@v4
#      - name: "🔧 Setup"
#        uses: ./.github/actions/use-flutter-dependencies
#      - name: "🏗️ Build ios"
#        run: flutter build ios --release --no-codesign

  tests:
    name: "Tests"
    needs: [validate_pr_title]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🧪 Test"
        run: flutter test
