name: "Pull Request Checks"

on:
  pull_request:

jobs:
  ##
  # install
  ##

  install_ubuntu:
    name: "Install On Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies

  install_macos:
    name: "Install On macOS"
    runs-on: macos-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies

  ##
  # validation
  ##

  validate_pr_title:
    name: "Validate PR Title"
    needs: [install_ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "✅ Validate"
        run: echo ${{ github.event.pull_request.title }} | dart run commitlint_cli

  ##
  # build
  ##

  build_android:
    name: "Build Android"
    needs: [install_ubuntu, validate_pr_title]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🏗️ Build AppBundle"
        run: flutter build aab --debug

  build_ios:
    name: "Build iOS"
    needs: [install_macos, validate_pr_title]
    runs-on: macos-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🏗️ Build ios"
        run: flutter build ios --debug --no-codesign

  tests:
    name: "Tests"
    needs: [install_ubuntu, validate_pr_title]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-flutter-dependencies
      - name: "🧪 Test"
        run: flutter test
