name: "Release - Production"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "🔖 Release"
    uses: ./.github/workflows/release.yml
    with:
      environment: "production"
    secrets:
      APK_SIGNING_KEY_ALIAS: ${{ secrets.APK_SIGNING_KEY_ALIAS }}
      APK_SIGNING_KEY_PASSWORD: ${{ secrets.APK_SIGNING_KEY_PASSWORD }}
      APK_SIGNING_KEYSTORE: ${{ secrets.APK_SIGNING_KEYSTORE }}
      APK_SIGNING_KEYSTORE_PASSWORD: ${{ secrets.APK_SIGNING_KEYSTORE_PASSWORD }}
      READ_AND_WRITE_REPOS_TOKEN: ${{ secrets.READ_AND_WRITE_REPOS_TOKEN }}
